const fs = require('fs');

const ONEPLUS_DEFS = `  oneplus: [
    {
      id: 'oneplus-13-12',
      slug: 'oneplus-13-12-series',
      name: 'OnePlus 13 & 12 Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg',
      description: 'OnePlus 13, 12, 12R',
      pattern: /\\b(oneplus\\s*(13|12)|12r)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 13 & 12 Series', model: 'OnePlus 13', storage: '256 GB', price: 62000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 13 & 12 Series', model: 'OnePlus 12 5G', storage: '256 GB', price: 46000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 13 & 12 Series', model: 'OnePlus 12R 5G', storage: '128 GB', price: 31000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg' },
      ],
    },
    {
      id: 'oneplus-11',
      slug: 'oneplus-11-series',
      name: 'OnePlus 11 Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-11.jpg',
      description: 'OnePlus 11 5G, 11R 5G',
      pattern: /\\b(oneplus\\s*11|11r)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 11 Series', model: 'OnePlus 11 5G', storage: '128 GB', price: 34000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-11.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 11 Series', model: 'OnePlus 11R 5G', storage: '128 GB', price: 24000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-11r.jpg' },
      ],
    },
    {
      id: 'oneplus-10',
      slug: 'oneplus-10-series',
      name: 'OnePlus 10 Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10-pro.jpg',
      description: 'OnePlus 10 Pro, 10T, 10R',
      pattern: /\\b(oneplus\\s*10|10t|10r)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 10 Series', model: 'OnePlus 10 Pro 5G', storage: '128 GB', price: 26000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10-pro.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 10 Series', model: 'OnePlus 10T 5G', storage: '128 GB', price: 21000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10t-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 10 Series', model: 'OnePlus 10R 150W', storage: '256 GB', price: 18500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10r-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 10 Series', model: 'OnePlus 10R 5G', storage: '128 GB', price: 16500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10r-5g.jpg' },
      ],
    },
    {
      id: 'oneplus-9',
      slug: 'oneplus-9-series',
      name: 'OnePlus 9 Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro-.jpg',
      description: 'OnePlus 9 Pro, 9, 9RT, 9R',
      pattern: /\\b(oneplus\\s*9|9r|9rt)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 9 Series', model: 'OnePlus 9 Pro 5G', storage: '128 GB', price: 20000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro-.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 9 Series', model: 'OnePlus 9 5G', storage: '128 GB', price: 16000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 9 Series', model: 'OnePlus 9RT 5G', storage: '128 GB', price: 15000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9rt-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 9 Series', model: 'OnePlus 9R 5G', storage: '128 GB', price: 13500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9r.jpg' },
      ],
    },
    {
      id: 'oneplus-8-7',
      slug: 'oneplus-8-7-series',
      name: 'OnePlus 8 & 7 Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-8-pro.jpg',
      description: '8 Pro, 8T, 8, 7T Pro, 7T, 7',
      pattern: /\\b(oneplus\\s*(8|7)|7t|8t)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 8 Pro', storage: '128 GB', price: 14500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-8-pro.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 8T 5G', storage: '128 GB', price: 12500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-8t.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 8 5G', storage: '128 GB', price: 11000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-8.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 7T Pro', storage: '256 GB', price: 10500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-7t-pro.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 7T', storage: '128 GB', price: 9000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-7t.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 7 Pro', storage: '128 GB', price: 9500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-7-pro.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 8 & 7 Series', model: 'OnePlus 7', storage: '128 GB', price: 7500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-7.jpg' },
      ],
    },
    {
      id: 'oneplus-nord',
      slug: 'oneplus-nord-series',
      name: 'OnePlus Nord Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-4-5g.jpg',
      description: 'Nord 4, Nord 3, Nord 2T, Nord CE 4...',
      pattern: /\\bnord\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord 4 5G', storage: '128 GB', price: 23000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-4-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord 3 5G', storage: '128 GB', price: 16500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-3r.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord 2T 5G', storage: '128 GB', price: 13000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-2t.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord 2 5G', storage: '128 GB', price: 10500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-2-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 4 5G', storage: '128 GB', price: 17000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce4-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 4 Lite 5G', storage: '128 GB', price: 13500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce4-lite.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 3 5G', storage: '128 GB', price: 12500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce3-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 3 Lite 5G', storage: '128 GB', price: 11000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-3-lite.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 2 5G', storage: '128 GB', price: 9500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-2-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 2 Lite 5G', storage: '128 GB', price: 8500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-2-lite-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord CE 5G', storage: '128 GB', price: 7500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-5g.jpg' },
        { brand: 'OnePlus', series: 'OnePlus Nord Series', model: 'OnePlus Nord', storage: '128 GB', price: 7000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord.jpg' },
      ],
    },
    {
      id: 'oneplus-open',
      slug: 'oneplus-open-series',
      name: 'OnePlus Open Foldable',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-open.jpg',
      description: 'OnePlus Open Flagship Foldable',
      pattern: /\\bopen\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus Open Foldable', model: 'OnePlus Open', storage: '512 GB', price: 78000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-open.jpg' },
      ],
    },
    {
      id: 'oneplus-classic',
      slug: 'oneplus-classic-series',
      name: 'OnePlus 6 & Classic Series',
      brand: 'OnePlus',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-6t.jpg',
      description: '6T, 6, 5T, 5, 3T, 3, One',
      pattern: /\\b(oneplus\\s*(6|5|3|2|1|one)|6t|5t|3t)\\b/i,
      defaultModels: [
        { brand: 'OnePlus', series: 'OnePlus 6 & Classic Series', model: 'OnePlus 6T', storage: '128 GB', price: 6200, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-6t.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 6 & Classic Series', model: 'OnePlus 6', storage: '64 GB', price: 5000, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-6.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 6 & Classic Series', model: 'OnePlus 5T', storage: '64 GB', price: 4200, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-5t.jpg' },
        { brand: 'OnePlus', series: 'OnePlus 6 & Classic Series', model: 'OnePlus 5', storage: '64 GB', price: 3500, image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-5.jpg' },
      ],
    },
  ],`;

const XIAOMI_DEFS = `  xiaomi: [
    {
      id: 'xiaomi-flagship',
      slug: 'xiaomi-flagship-series',
      name: 'Xiaomi Mi / Flagship Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg',
      description: 'Xiaomi 14 Ultra, 14, 13 Pro, 12 Pro...',
      pattern: /\\b(xiaomi\\s*(14|13|12|11)|mi\\s*\\d+|civi)\\b/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 14 Ultra', storage: '512 GB', price: 68000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 14', storage: '256 GB', price: 44000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 14 Civi', storage: '256 GB', price: 32000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-civi.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 13 Pro 5G', storage: '256 GB', price: 36000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13-pro.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 12 Pro 5G', storage: '256 GB', price: 23000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-12-pro.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Xiaomi 11T Pro 5G', storage: '128 GB', price: 16000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-11t-pro.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Mi 11X Pro 5G', storage: '128 GB', price: 13500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-11x-pro.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Mi 11X 5G', storage: '128 GB', price: 11500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-11x.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Mi 10T Pro 5G', storage: '128 GB', price: 11000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-10t-pro-5g.jpg' },
        { brand: 'Xiaomi', series: 'Xiaomi Mi / Flagship Series', model: 'Mi 10 5G', storage: '128 GB', price: 10000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-10-5g.jpg' },
      ],
    },
    {
      id: 'redmi-note-13',
      slug: 'redmi-note-13-series',
      name: 'Redmi Note 13 Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-plus.jpg',
      description: 'Note 13 Pro+, Note 13 Pro, Note 13',
      pattern: /note\\s*13/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'Redmi Note 13 Series', model: 'Redmi Note 13 Pro+ 5G', storage: '256 GB', price: 19500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-plus.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 13 Series', model: 'Redmi Note 13 Pro 5G', storage: '128 GB', price: 15500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 13 Series', model: 'Redmi Note 13 5G', storage: '128 GB', price: 12000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13.jpg' },
      ],
    },
    {
      id: 'redmi-note-12',
      slug: 'redmi-note-12-series',
      name: 'Redmi Note 12 Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro-plus.jpg',
      description: 'Note 12 Pro+, Note 12 Pro, Note 12',
      pattern: /note\\s*12/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'Redmi Note 12 Series', model: 'Redmi Note 12 Pro+ 5G', storage: '256 GB', price: 15000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro-plus.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 12 Series', model: 'Redmi Note 12 Pro 5G', storage: '128 GB', price: 12500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 12 Series', model: 'Redmi Note 12 5G', storage: '128 GB', price: 9500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 12 Series', model: 'Redmi Note 12 4G', storage: '64 GB', price: 8000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-4g.jpg' },
      ],
    },
    {
      id: 'redmi-note-11-older',
      slug: 'redmi-note-11-series',
      name: 'Redmi Note 11 & Older Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-pro-plus-5g.jpg',
      description: 'Note 11, 10, 9, 8, 7...',
      pattern: /note\\s*(11|10|[4-9])/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 11 Pro+ 5G', storage: '128 GB', price: 10500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-pro-plus-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 11 Pro', storage: '128 GB', price: 9000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-pro.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 11S', storage: '64 GB', price: 8000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11s.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 11', storage: '64 GB', price: 7200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 10 Pro Max', storage: '128 GB', price: 8500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-10-pro-max.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 10 Pro', storage: '128 GB', price: 7500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-10-pro.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 10', storage: '64 GB', price: 6200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-10.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 9 Pro Max', storage: '64 GB', price: 5800, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-9-pro-max.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 9 Pro', storage: '64 GB', price: 5200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-9-pro.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Note 11 & Older Series', model: 'Redmi Note 8 Pro', storage: '64 GB', price: 4500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-8-pro.jpg' },
      ],
    },
    {
      id: 'poco-series',
      slug: 'poco-series',
      name: 'POCO Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg',
      description: 'X6 Pro, X5, F6, F5, M6...',
      pattern: /\\bpoco\\b/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco F6 5G', storage: '256 GB', price: 21000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f6.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco F5 5G', storage: '256 GB', price: 16500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f5.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco X6 Pro 5G', storage: '256 GB', price: 18000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco X6 5G', storage: '128 GB', price: 13500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco X5 Pro 5G', storage: '128 GB', price: 12000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x5-pro.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco M6 Pro 5G', storage: '128 GB', price: 8500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-m6-pro-5g.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco M6 5G', storage: '64 GB', price: 7200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-m6-5g.jpg' },
        { brand: 'Xiaomi', series: 'POCO Series', model: 'Poco C65', storage: '128 GB', price: 6200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c65.jpg' },
      ],
    },
    {
      id: 'redmi-number',
      slug: 'redmi-number-series',
      name: 'Redmi Number Series',
      brand: 'Xiaomi',
      image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13-5g.jpg',
      description: 'Redmi 13 5G, 13C, 12 5G, 11 Prime...',
      pattern: /\\b(redmi\\s*\\d+|redmi\\s*a\\d+)\\b/i,
      defaultModels: [
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi 13 5G', storage: '128 GB', price: 9500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi 13C 5G', storage: '128 GB', price: 8000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13c-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi 12 5G', storage: '128 GB', price: 8200, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-12-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi 11 Prime 5G', storage: '64 GB', price: 6500, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-11-prime-5g.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi A3', storage: '64 GB', price: 4800, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-a3.jpg' },
        { brand: 'Xiaomi', series: 'Redmi Number Series', model: 'Redmi 10 Power', storage: '128 GB', price: 6000, image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-10-power.jpg' },
      ],
    },
  ],`;

console.log('Writing updated brandSeriesCatalog.ts and updating SellPhone.tsx...');
